import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from './Navbar';
import Footer from './Footer';
import FriendsProvider from './context/FriendsProvider'




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KeenFriends",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" data-theme='light'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <FriendsProvider>
          <Navbar></Navbar>
          <main className='bg-[#F8FAFC]'>
            {children}
            <ToastContainer />
          </main>
          <Footer></Footer>
        </FriendsProvider>
      </body>
    </html>
  );
}
